# Generated by Django 3.1.4 on 2020-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciver_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.IntegerField(),
        ),
    ]
